package ru.fueltracker.app.ui.theme

import androidx.compose.ui.graphics.Color

// Светлая тема: сине-бирюзовый основной цвет, янтарный акцент («топливо»)
val PrimaryLight = Color(0xFF00658E)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFC7E7FF)
val OnPrimaryContainerLight = Color(0xFF001E2E)
val SecondaryLight = Color(0xFF4F616E)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFD2E5F5)
val OnSecondaryContainerLight = Color(0xFF0B1D29)
val TertiaryLight = Color(0xFF825500)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFFFDDB3)
val OnTertiaryContainerLight = Color(0xFF291800)
val BackgroundLight = Color(0xFFF7F9FC)
val OnBackgroundLight = Color(0xFF181C20)
val SurfaceLight = Color(0xFFF7F9FC)
val OnSurfaceLight = Color(0xFF181C20)
val SurfaceVariantLight = Color(0xFFDDE3EA)
val OnSurfaceVariantLight = Color(0xFF41484D)

// Тёмная тема
val PrimaryDark = Color(0xFF84CFFF)
val OnPrimaryDark = Color(0xFF00344C)
val PrimaryContainerDark = Color(0xFF004C6C)
val OnPrimaryContainerDark = Color(0xFFC7E7FF)
val SecondaryDark = Color(0xFFB6C9D8)
val OnSecondaryDark = Color(0xFF21323E)
val SecondaryContainerDark = Color(0xFF374955)
val OnSecondaryContainerDark = Color(0xFFD2E5F5)
val TertiaryDark = Color(0xFFFFB951)
val OnTertiaryDark = Color(0xFF452B00)
val TertiaryContainerDark = Color(0xFF633F00)
val OnTertiaryContainerDark = Color(0xFFFFDDB3)
val BackgroundDark = Color(0xFF101417)
val OnBackgroundDark = Color(0xFFE0E3E8)
val SurfaceDark = Color(0xFF101417)
val OnSurfaceDark = Color(0xFFE0E3E8)
val SurfaceVariantDark = Color(0xFF41484D)
val OnSurfaceVariantDark = Color(0xFFC1C7CE)

// Цвет расхода по calc.consumption_status: NORMAL — зелёный, OVER — красный
val ConsumptionNormalLight = Color(0xFF2E7D32)
val ConsumptionOverLight = Color(0xFFC62828)
val ConsumptionNormalDark = Color(0xFF81C784)
val ConsumptionOverDark = Color(0xFFEF9A9A)
